# -*- coding: utf-8 -*-
"""Análise Escolaridade - florianópolis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LCrI6y9ctiF17YA2_25h3BraKqcXHvsh

INSTALAÇÃO DAS BIBLIOTECAS
"""

pip install gcsfs

pip install pandera

"""DECLARAÇÃO DAS LIBS"""

import pandas as pd
import os
import numpy as np
from google.cloud import storage
import pandera as pa

"""CONECTANDO COM O BUCKET"""

#CONFIGURANDO DA CHAVE DE SEGURANCA (Enviada com o projeto)

serviceAccount = '/content/squad-7-economia-613c7dc87c97.json'
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = serviceAccount

#Configurações Google Cloud Storage
client = storage.Client()
bucket = client.get_bucket('economy-squad-7')
bucket.blob('economy-squad-7/Tabelas escolaridade/RM 64200 Florianópolis - Base UDH 2000_2010.xlsx')
path = '/content/Tabelas escolaridade_filtradas_Tabela floripa - filtrada.csv'

"""EXTRAÇÃO DOS DADOS"""

df = pd.read_csv(path, sep=',', encoding='ISO-8859-1')

"""PRÉ-ANÁLISE"""

df

#Tam. do DF
df.shape

#Mostra das 5 primeiras linhas do df
df.head(5)

df.dtypes

#Visualiza valores unicos na coulna
pd.unique(df['NOME_UF'])

pd.unique(df['NOME_RM'])

pd.unique(df['NOME_MUN'])

"""TRANSFORMAÇÕES (LIMPEZAS ETC)"""

#Backup local(M.RAM) do df
dfback = df.copy()

#dropando a coluna NOME_UDH
df.drop(['NOME_UDH'],axis=1,inplace=True)

#dropar a coluna NOME_MUN?

#Verificando dados nulos, ausentes etc
df.isna().sum()

#CONVERTENDO O TIPO DE UMA COLUNA
df['coluna'] = df['coluna'].astype(str)

"""CRIAÇÃO DO SCHEMMA DE VALIDAÇÃO DE DADOS"""



"""BUSCAS (QUERY)"""



"""FILTROS"""



"""GROUPBY"""



"""PLOTAGENS"""



"""CARREGANDO O DF"""

#Utilizar se for o rotulo padrão
df.to_csv('cenipa_tratado_ok.csv',index=False)

#Enviando o novo df pro bucket
df.to_csv('gs://economy-squad-7/Tabelas escolaridade/filtradas/Tabela floripa - filtrada',index=False)