# -*- coding: utf-8 -*- 
"""Análise Escolaridade - são paulo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bhnR9Jwa-mv1ubvuvsZ6DOWWBpd4xD3k

INSTALAÇÃO DAS BIBLIOTECAS
"""

pip install gcsfs

pip install pandera

"""DECLARAÇÃO DAS LIBS"""

import pandas as pd
import os
import numpy as np
from google.cloud import storage
import pandera as pa

"""CONECTANDO COM O BUCKET"""

#CONFIGURANDO DA CHAVE DE SEGURANCA (Enviada com o projeto)

serviceAccount = '/content/squad-7-economia-613c7dc87c97.json'
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = serviceAccount

#Configurações Google Cloud Storage
client = storage.Client()
bucket = client.get_bucket('economy-squad-7')
bucket.blob('economy-squad-7/Tabelas escolaridade/csv/Tabelas escolaridade_RM 63500 São Paulo - Base UDH 2000_2010.xlsx - Sheet1.csv')
path = 'gs://economy-squad-7/Tabelas escolaridade/csv/Tabelas escolaridade_RM 63500 São Paulo - Base UDH 2000_2010.xlsx - Sheet1.csv'

"""EXTRAÇÃO DOS DADOS"""

df = pd.read_csv(path, sep=',')

"""PRÉ-ANÁLISE"""

df

#Tam. do DF
df.shape

#Mostra das 5 primeiras linhas do df
df.head(5)

df.dtypes

#criando um novo df com as colunas que importam
df_novo = df.loc[:, ['ANO', 'NOME_UDH', 'NOME_MUN', 'NOME_RM', 'NOME_UF', 'GINI',\
                     'I_ESCOLARIDADE', 'IDHM', 'IDHM_E', 'IDHM_L', 'IDHM_R', 'P_AGRO',\
                     'P_COM', 'P_CONSTR', 'P_EXTR', 'P_SERV', 'P_SIUP', 'P_TRANSF',\
                     'CPR', 'EMP', 'P_FORMAL', 'TRABCC', 'TRABPUB', 'TRABSC',\
                     'PEA18M', 'PESORUR', 'PESOTOT', 'PESOURB', 'PIA18M', 'R1040',\
                     'R2040', 'RDPC', 'RENOCUP', 'TRABCC', 'TRABPUB', 'THEILtrab', 'TRABSC',]]

df = df_novo

df.dtypes

#Visualiza valores unicos na coulna
pd.unique(df['NOME_UF'])

pd.unique(df['NOME_RM'])

pd.unique(df['NOME_MUN'])

"""TRANSFORMAÇÕES (LIMPEZAS ETC)"""

#Backup local(M.RAM) do df
dfback = df.copy()

#dropar a coluna NOME_MUN?

#Verificando dados nulos, ausentes etc
df.isna().sum()

#Filtrando os nulos
GINInulo = df.GINI.isna()
df.loc[GINInulo]

#Dropando os registros nulos
df = df.dropna()

df.dtypes

#Transformando as colunas em int pra combinar com as outras tabelas
df['PESORUR'] = df['PESORUR'].astype(int)
df['PESOTOT'] = df['PESOTOT'].astype(int)
df['PESOURB'] = df['PESOURB'].astype(int)

df.dtypes

df.isna().sum()

"""CRIAÇÃO DO SCHEMMA DE VALIDAÇÃO DE DADOS"""



"""BUSCAS (QUERY)"""



"""FILTROS"""



"""GROUPBY"""



"""PLOTAGENS"""



"""CARREGANDO O DF"""

#Enviando o novo df pro bucket
df.to_csv('gs://economy-squad-7/Tabelas escolaridade/filtradas/Tabela Sao Paulo - filtrada.csv',index=False)