# -*- coding: utf-8 -*-
"""conexão_mongo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h_DxafJ4qx1NwYL5keRZQaSk5HrZ4Qc0
"""

pip install gcsfs

pip install pandera

pip install pymongo

import pandas as pd
import os
import numpy as np
from google.cloud import storage
import pandera as pa
from pymongo import MongoClient

uri = "mongodb+srv://sevencapital.og7qt7f.mongodb.net/?authSource=%24external&authMechanism=MONGODB-X509&retryWrites=true&w=majority"
client = MongoClient(uri,
                     tls=True,
                     tlsCertificateKeyFile='/content/X509-cert-9181581684073656281.pem')

db = client['Squad7']
bruto = db['brutos']
tratado = db['tratado']

#CONFIGURANDO DA CHAVE DE SEGURANCA (Enviada com o projeto)

serviceAccount = '/content/squad-7-economia-5ec84694df36.json'
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = serviceAccount

#Configurações Google Cloud Storage
client = storage.Client()
bucket = client.get_bucket('economy-squad-7')
bucket.blob('economy-squad-7/Tabelas escolaridade/csv/Tabelas escolaridade_RM 63500 São Paulo - Base UDH 2000_2010.xlsx - Sheet1.csv')
#Brutos

#Const_Civil_Custos_médios (1).csv
path1 = 'gs://economy-squad-7/principal/Const_Civil_Custos_médios (1).csv'
#IDH 2010.csv
path2 = 'gs://economy-squad-7/principal/IDH 2010.csv'
#INDICE VENDA RESIDENCIAL.csv
path3 = 'gs://economy-squad-7/principal/INDICE VENDA RESIDENCIAL.csv'
#INDICEm2_bruto.csv
path4 = 'gs://economy-squad-7/principal/INDICEm2_bruto/INDICEm2_bruto.csv'
#anuario-2022.xlsx
path5 = 'https://storage.cloud.google.com/economy-squad-7/principal/anuario-2022.xlsx'
#operacoes-financiamento-operacoes-indiretas-automaticas.csv
path6 = 'gs://economy-squad-7/principal/operacoes-financiamento-operacoes-indiretas-automaticas.csv'
#operacoes-financiamento-operacoes-nao-automaticas.csv
path7 = 'https://storage.cloud.google.com/economy-squad-7/principal/operacoes-financiamento-operacoes-nao-automaticas.csv'
#preco_venda.csv
path8 = 'gs://economy-squad-7/principal/preco_venda.csv'
#principal_tabelas IDH_PIB dos Municípios - base de dados 2002-2009.csv
path9 = 'gs://economy-squad-7/principal/principal_tabelas IDH_PIB dos Municípios - base de dados 2002-2009.csv'
#principal_tabelas IDH_PIB dos Municípios - base de dados 2010-2020.csv
path10 = 'gs://economy-squad-7/principal/principal_tabelas IDH_PIB dos Municípios - base de dados 2010-2020.csv'
#principal_tabelas IDH_principal_tabelas IDH_tabelas_completas.csv
path11 = 'gs://economy-squad-7/principal/principal_tabelas IDH_principal_tabelas IDH_tabelas_completas.csv'
#principal_tabelas IDH_tabelas_completas.csv
path12 = 'gs://economy-squad-7/principal/tabelas IDH/principal_tabelas IDH_tabelas_completas.csv'
#venda_capitais.csv
path13 = 'gs://economy-squad-7/principal/venda_capitais.csv'

#TRATADOS
#BNDES_FINANCIEAMENTOS_5RM.csv
path14 = 'gs://economy-squad-7/PRONTO PARA ANALISE/BNDES_FINANCIEAMENTOS_5RM.csv'
#IBGE_POPULACAO_SALARIOMEDIO_EMPREGO_MORTALIDADE.csv
path15 = 'gs://economy-squad-7/PRONTO PARA ANALISE/IBGE_POPULACAO_SALARIOMEDIO_EMPREGO_MORTALIDADE.csv'
#IDH_2010_5RM.csv
path16 = 'gs://economy-squad-7/PRONTO PARA ANALISE/IDH_2010_5RM.csv'
#PIB_5RM_PRINCIPAIS.csv
path17 = 'gs://economy-squad-7/PRONTO PARA ANALISE/PIB_5RM_PRINCIPAIS.csv'
#bndes_com_consulta_filtrada_UF.csv
path18 = 'gs://economy-squad-7/PRONTO PARA ANALISE/bndes_com_consulta_filtrada_UF.csv'
#custo_m2_constcivil_5RM.csv
path19 = 'gs://economy-squad-7/PRONTO PARA ANALISE/custo_m2_constcivil_5RM.csv'
#preco_venda.csv
path20 = 'gs://economy-squad-7/PRONTO PARA ANALISE/preco_venda.csv'
#tabela_credito_auto_tratada_filtrada.csv
path21 = 'gs://economy-squad-7/PRONTO PARA ANALISE/tabela_credito_auto_tratada_filtrada.csv'
#tabelas_filtradas_bndes_com_consulta_filtrada_UF.csv
path22 = 'gs://economy-squad-7/PRONTO PARA ANALISE/tabelas_filtradas_bndes_com_consulta_filtrada_UF.csv'
#variacao_anual_5estados.csv
path23 = 'gs://economy-squad-7/PRONTO PARA ANALISE/variacao_anual_5estados.csv'

df1 = pd.read_csv(path1, sep=',')
df2 = pd.read_csv(path2, sep=',')
df4 = pd.read_csv(path4, sep=',')
df5 = pd.read_csv(path5, sep=';')
df6 = pd.read_csv(path6, sep=';')

df7 = pd.read_csv(path7, sep=';')
df8 = pd.read_csv(path8, sep=',')
df9 = pd.read_csv(path9, sep=';', encoding='latin-1')
df10 = pd.read_csv(path10, sep=';', encoding='latin-1')
df11 = pd.read_csv(path11, sep=';', encoding='latin-1')
df12 = pd.read_csv(path12, sep=';', encoding='latin-1')
df13 = pd.read_csv(path13, sep=',')
df14 = pd.read_csv(path14, sep=',')
df15 = pd.read_csv(path15, sep=',')
df16 = pd.read_csv(path16, sep=',')
df17 = pd.read_csv(path17, sep=',')
df18 = pd.read_csv(path18, sep=',')
df19 = pd.read_csv(path19, sep=',')
df20 = pd.read_csv(path20, sep=',')
df21 = pd.read_csv(path21, sep=',')
df22 = pd.read_csv(path22, sep=',')
df23 = pd.read_csv(path23, sep=',')

"""##Enviando para o mongo"""

df_1 = df1.to_dict("records")
bruto.insert_many(df_1)
df_2 = df2.to_dict("records")
bruto.insert_many(df_2)
df_4 = df4.to_dict("records")
bruto.insert_many(df_4)
df_5 = df5.to_dict("records")
bruto.insert_many(df_5)
df_7 = df7.to_dict("records")
bruto.insert_many(df_7)
df_8 = df8.to_dict("records")
bruto.insert_many(df_8)
df_9 = df9.to_dict("records")
bruto.insert_many(df_9)
df_10 = df10.to_dict("records")
bruto.insert_many(df_10)
df_11 = df11.to_dict("records")
bruto.insert_many(df_11)
df_12 = df12.to_dict("records")
bruto.insert_many(df_12)
df_13 = df13.to_dict("records")
bruto.insert_many(df_13)
df_15 = df15.to_dict("records")
tratado.insert_many(df_15)
df_16 = df16.to_dict("records")
tratado.insert_many(df_16)
df_17 = df17.to_dict("records")
tratado.insert_many(df_17)
df_18 = df18.to_dict("records")
tratado.insert_many(df_18)
df_19 = df19.to_dict("records")
tratado.insert_many(df_19)
df_20 = df20.to_dict("records")
tratado.insert_many(df_20)
df_21 = df21.to_dict("records")
tratado.insert_many(df_21)
df_22 = df22.to_dict("records")
tratado.insert_many(df_22)
df_23 = df23.to_dict("records")
tratado.insert_many(df_23)