# -*- coding: utf-8 -*-
"""vendas_por_cidade_PROJETO.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eCFiU8SM7ujPZnWmU8p1JqsfzHAVo-YL
"""

pip install gcsfs

pip install pandera

"""##Instalação de bibliotecas"""

import pandas as pd
import os
import numpy as np
from google.cloud import storage
import pandera as pa

"""#Configurando o Google Cloud"""

#CONFIGURANDO DA CHAVE DE SEGURANCA (Enviada com o projeto)

serviceAccount = '/content/squad-7-economia-5ec84694df36.json'
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = serviceAccount

#Configurações Google Cloud Storage
client = storage.Client()
bucket = client.get_bucket('economy-squad-7')
path = 'gs://economy-squad-7/tabelas_filtradas/vendas_por_cidade_filtrado - Página1.csv'

df = pd.read_csv(path, sep=',', encoding='ISO-8859-1')

"""#Pré-Análise"""

df

#Tam. do DF
df.shape

#As primeiras 5 linhas
df.head(5)

#Tipo das colunas
df.dtypes

"""#Limpeza"""

#Backup local(M.RAM) do df
dfback = df.copy()

#Verificação de valores dintintos na coluna Cidade
df['CIDADE'].unique()

#Renomeando as colunas
df = df.rename(columns={'MÃS':'MES','NÃMERO DE VENDAS':'NUMERO_DE_VENDAS'})

#Renomeando linhas
df.loc[df.CIDADE== 'SÃ\x83O PAULO',['CIDADE']] = 'SAO PAULO'
df.loc[df.CIDADE== 'FLORIANÃ\x93POLIS',['CIDADE']] = 'FLORIANOPOLIS'
df.loc[df.CIDADE== 'SÃ\x83O JOSÃ\x89 DOS CAMPOS',['CIDADE']] = 'SAO JOSE DOS CAMPOS'
df.loc[df.CIDADE== 'RIBEIRÃ\x83O PRETO',['CIDADE']] = 'RIBEIRAO PRETO'

df

#Verificando dados nulos, ausentes etc
df.isna().sum()



"""##Enviando para o bucket"""

df.to_csv('vendas_por_cidade_PROJETO - Página1.csv',index=False)

#Carregar direto no bucket
df.to_csv('gs://economy-squad-7/tabelas_filtradas/vendas_por_cidade_PROJETO - Página1.csv',index=False)

df